import fs from "node:fs";
import path from "node:path";

const FEATURES_DIR = path.join(process.cwd(), "docs/specs/features");
const INDEX_PATH = path.join(FEATURES_DIR, "_index.md");
const START_MARKER =
	"<!-- AUTO-GENERATED:START (run `pnpm spec:sync` — do not edit) -->";
const END_MARKER = "<!-- AUTO-GENERATED:END -->";

type FeatureRow = {
	feature: string;
	status: string;
	dependsOn: string;
};

function parseFrontmatter(raw: string): Record<string, string> {
	const match = raw.match(/^---\n([\s\S]*?)\n---/);
	const frontmatterBlock = match?.[1];
	if (!frontmatterBlock) return {};
	const fields: Record<string, string> = {};
	for (const line of frontmatterBlock.split("\n")) {
		const colonIndex = line.indexOf(":");
		if (colonIndex === -1) continue;
		fields[line.slice(0, colonIndex).trim()] = line
			.slice(colonIndex + 1)
			.trim();
	}
	return fields;
}

function formatList(value: string | undefined): string {
	const inner = value?.replace(/^\[|\]$/g, "").trim();
	if (!inner) return "—";
	return inner
		.split(",")
		.map((item) => item.trim())
		.filter(Boolean)
		.join(", ");
}

function readFeatureRows(): FeatureRow[] {
	if (!fs.existsSync(FEATURES_DIR)) return [];
	const rows: FeatureRow[] = [];
	for (const entry of fs.readdirSync(FEATURES_DIR, { withFileTypes: true })) {
		if (!entry.isDirectory()) continue;
		const specPath = path.join(FEATURES_DIR, entry.name, "spec.md");
		if (!fs.existsSync(specPath)) continue;
		const frontmatter = parseFrontmatter(fs.readFileSync(specPath, "utf-8"));
		rows.push({
			feature: frontmatter.feature ?? entry.name,
			status: frontmatter.status ?? "unknown",
			dependsOn: formatList(frontmatter["depends-on"]),
		});
	}
	return rows.sort((a, b) => a.feature.localeCompare(b.feature));
}

function renderTable(rows: FeatureRow[]): string {
	const header = "| Feature | Status | Depends on |\n|---|---|---|";
	if (rows.length === 0) {
		return `${header}\n| _(no features yet)_ | — | — |`;
	}
	const lines = rows.map(
		(row) => `| ${row.feature} | ${row.status} | ${row.dependsOn} |`,
	);
	return [header, ...lines].join("\n");
}

function writeIndex(rows: FeatureRow[]): void {
	const block = `${START_MARKER}\n${renderTable(rows)}\n${END_MARKER}`;

	if (!fs.existsSync(INDEX_PATH)) {
		fs.mkdirSync(FEATURES_DIR, { recursive: true });
		const content = `# Feature Index

Generated by \`pnpm spec:sync\` from \`docs/specs/features/*/spec.md\` frontmatter. Do not edit
this table by hand — edit the relevant \`spec.md\`'s frontmatter and re-run \`pnpm spec:sync\`.

${block}
`;
		fs.writeFileSync(INDEX_PATH, content);
		console.log(`Created ${INDEX_PATH}`);
		return;
	}

	const existing = fs.readFileSync(INDEX_PATH, "utf-8");
	const startIdx = existing.indexOf(START_MARKER);
	const endIdx = existing.indexOf(END_MARKER);
	if (startIdx === -1 || endIdx === -1) {
		throw new Error(
			`${INDEX_PATH} is missing its AUTO-GENERATED markers — restore them before running spec:sync.`,
		);
	}
	const updated =
		existing.slice(0, startIdx) +
		block +
		existing.slice(endIdx + END_MARKER.length);
	fs.writeFileSync(INDEX_PATH, updated);
	console.log(
		`Updated ${INDEX_PATH} (${rows.length} feature${rows.length === 1 ? "" : "s"})`,
	);
}

function main(): void {
	writeIndex(readFeatureRows());
}

main();
